# Generated by Django 4.2.5 on 2024-01-02 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_hotelbooking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.room'),
        ),
    ]
